version: "3.1"
   
services:
# So this is the web vote container - should be able to take votes in and put into queu
  nginx:
    build: .
    ports:
      - 8001:80
    volumes:
      - ./src:/usr/share/nginx/html

# This is the db with all the elections in

  db:
    image: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: flaskweb
    expose:
      - 5000
#    ports:
#      - 5000:5000
